name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3<% if (pnpm) { %>
      - uses: pnpm/action-setup@v2
        with:
          version: 8<% } %>
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Lint
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> lint

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3<% if (pnpm) { %>
      - uses: pnpm/action-setup@v2
        with:
          version: 8<% } %>
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Run Tests
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %> test
